-- MySQL Script generated by MySQL Workbench
-- Птн 21 мая 2021 12:44:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cargo_servlet_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `cargo_servlet_db` ;

-- -----------------------------------------------------
-- Table `cargo_servlet_db`.`tariffs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo_servlet_db`.`tariffs` ;

CREATE TABLE IF NOT EXISTS `cargo_servlet_db`.`tariffs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT UNSIGNED NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `size` VARCHAR(255) NOT NULL,
  `weight` VARCHAR(255) NOT NULL,
  `delivery_term_days` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargo_servlet_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo_servlet_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `cargo_servlet_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargo_servlet_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo_servlet_db`.`users` ;

CREATE TABLE IF NOT EXISTS `cargo_servlet_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_Users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `cargo_servlet_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cargo_servlet_db`.`users` create user with role 'ADMIN'
-- -----------------------------------------------------

insert into `users` (id, username, email, password, role_id) values
(1, 'admin', 'admin@google.com', '21232f297a57a5a743894a0e4a801fc3', 2);

-- -----------------------------------------------------
-- Table `cargo_servlet_db`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo_servlet_db`.`status` ;

CREATE TABLE IF NOT EXISTS `cargo_servlet_db`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;




insert into status (id, name) values
(1, 'NEW'),
(2, 'WAITING_FOR_PAYMENT'),
(3, 'PAID'),
(4, 'REJECTED');

-- -----------------------------------------------------
-- Table `cargo_servlet_db`.`transportations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo_servlet_db`.`transportations` ;

CREATE TABLE IF NOT EXISTS `cargo_servlet_db`.`transportations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `tariff_id` INT NOT NULL,
  `created_at` DATE NOT NULL,
  `delivery_at` DATE NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transportations_tariffs1_idx` (`tariff_id` ASC),
  INDEX `fk_transportations_Users1_idx` (`user_id` ASC),
  INDEX `fk_transportations_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_transportations_tariffs1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `cargo_servlet_db`.`tariffs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transportations_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cargo_servlet_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transportations_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `cargo_servlet_db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


--SET SQL_MODE=@OLD_SQL_MODE;
--SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
--SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
